/* =========================================================================
   PORTFOLIO DATA - Mark Zaki
   Generated by admin.html. You can still hand-edit this file by hand.
   ========================================================================= */

const PROFILE = {
  "name": "Mark Zaki",
  "roleWords": [
    "Gameplay Systems",
    "FishNet",
    "Photon Fusion",
    "Combat Design",
    "AI Systems"
  ],
  "tagline": "Gameplay & Multiplayer Systems Programmer",
  "about": "I enjoy solving tricky game systems and working with people who care about the details. If you are building something interesting and think I could help, feel free to get in touch.",
  "intro": "I make Unity games with a focus on how they feel and how they hold together, from multiplayer and combat to VR interactions and the tools behind them.",
  "stats": [
    {
      "value": "Unity / C#",
      "label": "Core Stack"
    },
    {
      "value": "Server-Auth",
      "label": "Multiplayer Model"
    },
    {
      "value": "Souls-like",
      "label": "Combat Focus"
    },
    {
      "value": "Data-Driven",
      "label": "Architecture"
    },
    {
      "value": "MVVM  / MVC",
      "label": "Ui Architecture"
    }
  ],
  "pillars": [
    {
      "title": "Networked Gameplay & Multiplayer",
      "body": "I have built server-authoritative game modes, inventories, lobbies, character selection, rankings, voice and text chat, and state synchronization with Photon PUN and Fusion."
    },
    {
      "title": "Data-Driven, Clean, Scalable Architecture",
      "body": "I build modular Unity architecture with decoupled systems, reusable state machines, and designer-friendly ScriptableObject workflows that stay clear as projects grow."
    },
    {
      "title": "Live Systems & Backend Integration",
      "body": "I have connected Unity projects to APIs, AI services, purchases, authentication, reporting, leaderboards, and moderation workflows used by active player communities."
    },
    {
      "title": "UI Frameworks with MVP and MVC",
      "body": "I have built reusable UI frameworks with MVP and MVC, including navigation, transitions, data binding, VR interface flows, and production tooling that reduced screen-building time by 70%."
    }
  ],
  "links": {
    "github": "https://github.com/Markzaki55",
    "resume": "assets/MARK_ZAKI_Resume.pdf",
    "linkedin": "https://www.linkedin.com/in/markzakimalak",
    "email": "mailto:markzakimalakzaki@gmail.com "
  },
  "stack": [
    "Unity",
    "C#",
    "Photon PUN 2",
    "Photon Fusion",
    "FishNet",
    "OpenXR",
    "XR Interaction Toolkit",
    "ScriptableObjects",
    "Animation Rigging",
    "Cinemachine 3",
    "Backend Integration",
    "UGUI",
    "UI Toolkit",
    "Playfab",
    "Git",
    "Custom .Net backend",
    "Performance Optimization",
    "REST APIs",
    "MVC / MVP"
  ],
  "copyright": "@ 2026 Mark Zaki",
  "layoutVersion": 4,
  "expertiseVersion": 1,
  "projectDataVersion": 1,
  "copyVersion": 3,
  "footerTagline": "Always happy to talk game systems.",
  "typeVersion": 2,
  "themeFoundationVersion": 1
};

const THEME = {
  "bg": "#101010",
  "bg2": "#101010",
  "surface": "#1b1b1b",
  "surface2": "#232323",
  "line": "#383838",
  "lineSoft": "#292929",
  "text": "#f2f2f2",
  "muted": "#ababab",
  "faint": "#7c7c7c",
  "accent": "#d0d0d0",
  "accentSoft": "#ececec",
  "accentDeep": "#777777",
  "fontSans": "\"DM Sans\", Arial, sans-serif",
  "fontHeading": "\"DM Sans\", Arial, sans-serif",
  "heroText": "#ffffff",
  "headingText": "#f2f2f2",
  "projectTitle": "#f2f2f2",
  "bodyText": "#ababab"
};

const PROJECTS = [
  {
    "id": "al-molazem",
    "title": "Al Molazem Ans",
    "subtitle": "Shipped Mobile Game · Programming Lead",
    "tagline": "A live Saudi Arabian cop simulation game where I led gameplay programming and built scalable systems used by a large active player base.",
    "tags": [
      "Unity",
      "Leadership",
      "Live Systems",
      "Backend"
    ],
    "featured": true,
    "cover": {
      "type": "image",
      "label": "AL MOLAZEM",
      "sub": "Mobile Cop Simulation",
      "src": "assets/media/al-molazem-cover.png"
    },
    "role": "Programming Lead",
    "timeline": "Shipped / Live",
    "techStack": "Unity, C#, backend and web API integration",
    "media": [
      {
        "type": "youtube",
        "label": "GAMEPLAY",
        "sub": "Main gameplay overview or trailer",
        "label2": "Gameplay Overview",
        "featured": true,
        "id": "9RrQcm1aqts"
      },
      {
        "type": "image",
        "label": "REPORTS",
        "sub": "Traffic reporting flow and player interaction",
        "label2": "Traffic Reporting",
        "src": "assets/media/al-molazem-media-1.png"
      },
      {
        "type": "image",
        "label": "DASHBOARD",
        "sub": "Web moderation dashboard and live report data",
        "label2": "Moderation Dashboard",
        "src": "assets/media/al-molazem-media-2.png"
      },
      {
        "type": "image",
        "label": "LIVE OPS",
        "sub": "Live systems, player services, or team workflow",
        "label2": "Report Moderation",
        "src": "assets/media/al-molazem-media-3.png"
      },
      {
        "type": "image",
        "src": "assets/media/al-molazem-media-4.png",
        "label2": "Main Menu"
      }
    ],
    "sections": [
      {
        "heading": "Overview",
        "body": "Al Molazem is a shipped Saudi Arabian cop simulation game with a large active player community. I worked as Programming Lead, owning gameplay architecture while coordinating closely with design, art, backend, and engineering."
      },
      {
        "heading": "Technical Leadership",
        "body": "I led a six-person gameplay programming team, planned and reviewed core systems, mentored teammates, and kept implementation quality consistent as the game continued to grow."
      },
      {
        "heading": "Live Operations",
        "body": "I built an in-game traffic reporting system that processes more than 10,000 reports per day across a 60,000-player user base. Reports feed into a web moderation dashboard so the team can review and act on live player activity."
      },
      {
        "heading": "Commerce & Backend",
        "list": [
          "Integrated secure web purchases using Player ID with instant in-game delivery",
          "Reduced app store commission costs by 30%",
          "Integrated APIs for player accounts, purchases, and game services",
          "Resolved technical issues and optimized gameplay systems as new features were added"
        ]
      }
    ],
    "gallery": [],
    "links": []
  },
  {
    "id": "rd3",
    "title": "RD3",
    "subtitle": "Unannounced Multiplayer Third-Person Shooter",
    "tagline": "An unannounced multiplayer shooter with a five-mission campaign and a networked tower defense mode, developed with an 11-person team.",
    "tags": [
      "Unity",
      "Multiplayer",
      "TPS",
      "Game Systems"
    ],
    "featured": true,
    "cover": {
      "type": "image",
      "label": "RD3",
      "sub": "Unannounced Multiplayer TPS",
      "src": "assets/media/rd3-cover.png"
    },
    "role": "Gameplay & Multiplayer Programmer",
    "timeline": "Unannounced",
    "techStack": "Unity, C#, server-authoritative multiplayer, voice and text chat",
    "media": [
      {
        "type": "youtube",
        "label": "GAMEPLAY",
        "sub": "Campaign or multiplayer gameplay reel",
        "label2": "Gameplay Overview",
        "featured": true,
        "id": "YNJnOVU253Q"
      },
      {
        "type": "image",
        "src": "assets/media/rd3-media-1.png",
        "label2": "Main Menu"
      },
      {
        "type": "image",
        "src": "assets/media/rd3-media-2.png",
        "label2": ""
      },
      {
        "type": "youtube",
        "id": "kEcDNcNjdOY",
        "label2": "Network Helicopter Test"
      },
      {
        "type": "image",
        "src": "assets/media/rd3-media-4.png"
      },
      {
        "type": "image",
        "src": "assets/media/rd3-media-5.png",
        "label2": "Character Selection"
      },
      {
        "type": "image",
        "src": "assets/media/rd3-media-6.png",
        "label2": "Mission Selection"
      }
    ],
    "sections": [
      {
        "heading": "Overview",
        "body": "RD3 is an unannounced multiplayer third-person shooter with a five-mission campaign and a wave-based tower defense mode. I worked within an 11-person cross-discipline team to build networked gameplay, reusable UI architecture, and performance improvements."
      },
      {
        "heading": "Tower Defense Mode",
        "body": "I designed and built the networked tower defense mode, including enemy spawning, wave progression, rewards, and synchronized state across six enemy types and 15 increasingly difficult waves."
      },
      {
        "heading": "Multiplayer Systems",
        "list": [
          "Built the networked inventory, item pickup, and player ranking systems",
          "Adapted single-player mechanics for server authority and synchronized multiplayer state",
          "Built character selection and lobby flows with voice and text chat",
          "Implemented additional networked gameplay features, including helicopters"
        ]
      },
      {
        "heading": "UI & Performance",
        "list": [
          "Designed a reusable MVP UI framework that reduced screen-building time by 70%",
          "Streamlined navigation, transitions, and data binding for programmers and designers",
          "Reduced scene load time by 60% through memory and loading optimization"
        ]
      }
    ],
    "gallery": [],
    "links": []
  },
  {
    "id": "ruf",
    "title": "Radiant Undead Framework",
    "subtitle": "Personal Project · Third-Person Action RPG Framework",
    "tagline": "A modular Unity action RPG framework built around reusable combat, AI, traversal, animation, and multiplayer systems.",
    "tags": [
      "Unity",
      "Combat",
      "AI",
      "Architecture"
    ],
    "featured": true,
    "cover": {
      "type": "text",
      "label": "RUF",
      "sub": "Action RPG Framework"
    },
    "role": "Solo Developer / Systems Engineer",
    "timeline": "Personal Project",
    "techStack": "Unity, C#, ScriptableObjects, Photon PUN, Animation Rigging, Cinemachine 3, Unity Input System",
    "media": [
      {
        "type": "text",
        "label": "COMBAT",
        "sub": "Combat reel with attacks, parries, and feedback",
        "label2": "Combat Reel",
        "featured": true
      },
      {
        "type": "text",
        "label": "ENEMY AI",
        "sub": "Perception, decisions, and coordinated combat",
        "label2": "Enemy AI"
      },
      {
        "type": "text",
        "label": "TRAVERSAL",
        "sub": "Vault, mantle, climb, and wall-run systems",
        "label2": "Traversal"
      },
      {
        "type": "text",
        "label": "IK",
        "sub": "Hand, foot, and head IK in motion",
        "label2": "Animation & IK"
      },
      {
        "type": "text",
        "label": "MULTIPLAYER",
        "sub": "Character switching and synchronized state",
        "label2": "Multiplayer Systems"
      }
    ],
    "sections": [
      {
        "heading": "Overview",
        "body": "Radiant Undead Framework is a data-driven third-person action RPG framework inspired by Dark Souls and Elden Ring. I built it as a long-term systems project, with decoupled modules that can grow independently without turning the project into a tightly connected monolith."
      },
      {
        "heading": "Architecture",
        "list": [
          "Designer-friendly configuration built around ScriptableObjects",
          "Generic StateMachine<TOwner> architecture shared by player, enemy, and UI systems",
          "Decoupled systems designed to remain independently extensible",
          "Data-driven stats, buffs, abilities, and equipment"
        ]
      },
      {
        "heading": "Combat & Character Systems",
        "list": [
          "Souls-like charged attacks and stat scaling across seven character attributes",
          "Sekiro-style impact VFX, hitstop, and parry-window feedback",
          "Full hand, foot, and head IK with smooth weight transitions",
          "Vault, mantle, climb, and wall-run traversal using Motion Warping"
        ]
      },
      {
        "heading": "AI & Multiplayer",
        "list": [
          "Faction-agnostic enemy AI using blackboards, sensors, layered state machines, and priority-based decisions",
          "Coordinated group combat behavior",
          "Photon PUN multiplayer with runtime character-class switching",
          "Server-authoritative state synchronization"
        ]
      }
    ],
    "gallery": [],
    "links": []
  },
  {
    "id": "hirequestvr",
    "title": "HireQuestVR",
    "subtitle": "Graduation Project · VR Interview Platform",
    "tagline": "A Meta Quest 3S interview simulator that combines immersive practice, dynamic AI interviews, and a mobile companion app.",
    "tags": [
      "Unity",
      "OpenXR",
      "VR",
      "AI Integration"
    ],
    "featured": true,
    "cover": {
      "type": "image",
      "label": "HIREQUEST",
      "sub": "VR Interview Platform",
      "src": "assets/media/hirequestvr-cover.png"
    },
    "role": "Unity / VR Developer",
    "timeline": "Graduation Project",
    "techStack": "Unity, C#, Meta Quest 3S, OpenXR, XR Interaction Toolkit, Photon PUN 2, Flutter, DeepSeek LLM, TTS / STT, REST APIs",
    "media": [
      {
        "type": "youtube",
        "label": "VR WALKTHROUGH",
        "sub": "Complete interview flow captured on Quest 3S",
        "label2": "VR Walkthrough",
        "featured": true,
        "id": "LKFkmpykXtw"
      },
      {
        "type": "image",
        "src": "assets/media/hirequestvr-media-1.png",
        "label2": "Interview Selection"
      },
      {
        "type": "image",
        "src": "assets/media/hirequestvr-media-2.png",
        "label2": "OTP",
        "name": "OTP"
      },
      {
        "type": "image",
        "src": "assets/media/hirequestvr-media-3.png",
        "label2": "Media"
      },
      {
        "type": "image",
        "src": "assets/media/hirequestvr-media-4.png",
        "label2": "Media"
      }
    ],
    "sections": [
      {
        "heading": "Overview",
        "body": "HireQuestVR is a multi-team graduation project that combines a Meta Quest 3S application, a Flutter companion app, and an AI-driven backend. The platform gives users a repeatable way to practice interviews across different scenarios before facing a real one."
      },
      {
        "heading": "Unity & VR Experience",
        "list": [
          "Built the complete Unity and VR side of the platform",
          "Implemented World Space UI, XR hand tracking, and custom near, far, and poke interactors",
          "Built a custom VR keyboard manager and readable headset-first interface flows",
          "Structured mission and interview selection using MVC"
        ]
      },
      {
        "heading": "AI, Voice & Pairing",
        "list": [
          "Integrated a fine-tuned DeepSeek LLM backend for dynamic questions, responses, and interviewer behavior",
          "Added TTS and STT for voice-driven interview interaction",
          "Designed OTP authentication to pair the Flutter companion app with the VR headset",
          "Integrated backend services through REST APIs"
        ]
      },
      {
        "heading": "Platform Features",
        "list": [
          "Delivered more than five interview scenarios across multiple environments",
          "Added selectable interviewer personalities and character models",
          "Built leaderboard, scoring, and post-interview feedback systems",
          "Supported Arabic and English layouts with RTL and LTR localization"
        ]
      }
    ],
    "gallery": [],
    "links": []
  },
  {
    "id": "faraque",
    "title": "Faraque",
    "subtitle": "2D Multiplayer Racing Platformer",
    "tagline": "A fast 2D multiplayer racing platformer with character progression, customization, abilities, and monetization systems.",
    "tags": [
      "Unity",
      "Photon Fusion",
      "Multiplayer",
      "2D"
    ],
    "featured": false,
    "cover": {
      "type": "text",
      "label": "FARAQUE",
      "sub": "Multiplayer Racing Platformer"
    },
    "role": "Gameplay & Multiplayer Programmer",
    "timeline": "",
    "techStack": "Unity, C#, Photon Fusion",
    "media": [
      {
        "type": "youtube",
        "label": "RACE",
        "sub": "Full multiplayer race and platforming gameplay",
        "label2": "Race Gameplay",
        "featured": true,
        "id": "wZNyxJ58oNU"
      },
      {
        "type": "text",
        "label": "MULTIPLAYER",
        "sub": "Photon Fusion race synchronization",
        "label2": "Multiplayer Racing"
      },
      {
        "type": "text",
        "label": "ABILITIES",
        "sub": "Ability pickups and race interactions",
        "label2": "Abilities & Pickups"
      },
      {
        "type": "text",
        "label": "CUSTOMIZATION",
        "sub": "Character selection and customization flow",
        "label2": "Character Customization"
      },
      {
        "type": "text",
        "label": "ENVIRONMENTS",
        "sub": "Different race environments and level mechanics",
        "label2": "Race Environments"
      }
    ],
    "sections": [
      {
        "heading": "Overview",
        "body": "Faraque is a 2D multiplayer racing platformer built around competitive races, varied environments, character progression, and ability-driven moment-to-moment play."
      },
      {
        "heading": "Multiplayer Gameplay",
        "list": [
          "Built the multiplayer racing flow using Photon Fusion",
          "Created multiple race environments with varied gameplay abilities",
          "Implemented interactive ability pickup boxes during races"
        ]
      },
      {
        "heading": "Progression & Monetization",
        "list": [
          "Implemented character selection and customization",
          "Integrated in-app purchases",
          "Connected progression and customization to the wider race experience"
        ]
      }
    ],
    "gallery": [],
    "links": []
  }
];
