/* =========================================================================
   PORTFOLIO DATA - Mark Zaki
   Generated by admin.html. You can still hand-edit this file by hand.
   ========================================================================= */

const PROFILE = {
  "name": "Mark Zaki",
  "roleWords": [
    "Gameplay Systems",
    "FishNet",
    "Photon Fusion",
    "Combat Design",
    "AI Systems"
  ],
  "tagline": "Gameplay & Multiplayer Systems Engineer",
  "heroTag": "Open to new projects & collaborations",
  "footerTagline": "Always happy to talk game systems.",
  "about": "I'm a gameplay and multiplayer engineer based in Egypt. I care about how a hit feels, whether a fight is fair, and writing code that doesn't fall apart when the next feature shows up. I'd rather ship something solid than polish something forever.",
  "intro": "I build the systems underneath a game: server-authoritative multiplayer, Souls-like combat that feels responsive, and the kind of modular setup that lets you add a feature without breaking three others. Most of my work lives in Unity and C#, and I like turning rough gameplay ideas into clean systems other people can actually build on.",
  "stats": [
    {
      "value": "Unity / C#",
      "label": "Core Stack"
    },
    {
      "value": "Server-Auth",
      "label": "Multiplayer Model"
    },
    {
      "value": "Souls-like",
      "label": "Combat Focus"
    },
    {
      "value": "Data-Driven",
      "label": "Architecture"
    },
    {
      "value": "MVVM  / MVC",
      "label": "Ui Architecture"
    }
  ],
  "pillars": [
    {
      "title": "Server-Authoritative Multiplayer",
      "body": "Server-authoritative netcode with Photon PUN and Fishnet. Class switching, avatar rebinding, weapon reparenting, and state sync that holds together when more than a couple of players show up."
    },
    {
      "title": "Combat Feel & Design",
      "body": "Souls-like and Sekiro-style combat: deflect and clash VFX, hitstop, charged attacks, stamina economies, and the small frame-level details that decide whether a hit feels good."
    },
    {
      "title": "Enemy AI & Behaviors",
      "body": "Layered AI built on blackboards and ScriptableObject-driven roles and factions, with priority-based decision making, combat-ring slotting, and custom steering for enemies that fly."
    },
    {
      "title": "Clean, Modular Systems",
      "body": "SOLID, inspector-configured, ScriptableObject-heavy systems. Generic state machines, event channels, and assembly definitions, set up so the next feature drops in without disturbing the last one."
    }
  ],
  "links": {
    "github": "https://github.com/Markzaki55",
    "resume": "assets/resume.pdf",
    "linkedin": "https://www.linkedin.com/in/markzakimalak",
    "email": "mailto:markzakimalakzaki@gmail.com "
  },
  "stack": [
    "Unity",
    "C#",
    "Photon PUN",
    "Fishnet",
    "Multiplayer Netcode",
    "ScriptableObjects",
    "State Machines",
    "Animation Rigging",
    "Cinemachine 3",
    "NavMesh & Steering",
    "Unity Input System",
    "UI Toolkit",
    "uGUI",
    "Addressables",
    "Git LFS",
    "C++",
    "VR / OpenXR",
    "Quest 3S"
  ],
  "copyright": ""
};

const THEME = {
  "bg": "#0b0c0d",
  "bg2": "#0d0e0f",
  "surface": "#121315",
  "surface2": "#17191b",
  "line": "#202225",
  "lineSoft": "#17181a",
  "text": "#ECECE7",
  "muted": "#9a9b95",
  "faint": "#62635e",
  "accent": "#E8A33D",
  "accentSoft": "#f0bd6e",
  "accentDeep": "#a86c1f"
};

const PROJECTS = [
  {
    "id": "ruf",
    "title": "Radiant Undead",
    "subtitle": "Action RPG · Combat · AI · Systems Architecture",
    "tagline": "A modular Souls-like action RPG framework I'm building solo in Unity, with combat, AI, IK, and traversal designed as reusable systems.",
    "tags": [
      "Unity",
      "C#",
      "Souls-like",
      "Systems Design"
    ],
    "featured": true,
    "cover": {
      "type": "text",
      "label": "RUF",
      "sub": "Radiant Undead Framework"
    },
    "role": "Solo Developer - Systems & Combat",
    "timeline": "Ongoing",
    "techStack": "Unity, C#, ScriptableObjects, Animation Rigging, Cinemachine 3",
    "media": [
      {
        "type": "text",
        "label": "RADIANT UNDEAD",
        "sub": "Featured combat reel goes here",
        "featured": true,
        "label2": "Combat Reel"
      },
      {
        "type": "text",
        "label": "AI",
        "sub": "Enemy AI breakdown clip"
      },
      {
        "type": "text",
        "label": "IK",
        "sub": "Procedural foot & hand IK"
      },
      {
        "type": "text",
        "label": "SHOT",
        "sub": "Screenshot"
      }
    ],
    "links": [
      {
        "text": "View on GitHub",
        "url": "https://github.com/MarkZaki/ruf"
      }
    ],
    "sections": [
      {
        "heading": "Overview",
        "body": "Radiant Undead is my long-running portfolio project: a modular, data-driven Souls-like that I built to be reused. Every major system, whether it's combat, enemy AI, procedural IK, or traversal, lives in its own self-contained namespace so I can drop it into another project without dragging the whole game along with it."
      },
      {
        "heading": "Combat",
        "body": "Sekiro-style sword clash and deflect VFX, hitstop on impact, charged attacks, and a stamina economy that actually limits you. I was going for weight and readability, so every exchange reads clearly and feels like a decision rather than button mashing."
      },
      {
        "heading": "Enemy AI",
        "list": [
          "Generic EnemyAgent plus a Blackboard data container",
          "ScriptableObject faction and role hierarchy with a relationship database",
          "Priority-based decision evaluator and runner",
          "CombatRing slot system so enemies attack in turns instead of swarming",
          "Custom steering (not NavMesh) for open-air flying enemies",
          "Idle behaviours: patrol, guard, box, and group patrol with alert states"
        ]
      },
      {
        "heading": "Animation & IK",
        "body": "A procedural FootIK system that handles height transitions cleanly and ramps in and out with SmoothDamp, plus a HandIK system with reach clamping and per-frame offset control. Animation Rigging multi-aim constraints handle look-at and aiming on top of that."
      }
    ],
    "gallery": []
  },
  {
    "id": "hirequest",
    "title": "HireQuestVR",
    "subtitle": "VR · AI · Graduation Project",
    "tagline": "A VR interview simulator built in Unity with an AI backend, so you can practice real interviews on a Quest 3S before the real thing.",
    "tags": [
      "Unity",
      "VR",
      "OpenXR",
      "AI Backend"
    ],
    "featured": true,
    "cover": {
      "type": "text",
      "label": "HIREQUEST",
      "sub": "VR Interview Simulation",
      "id": "hYa9Fc7bJuU"
    },
    "role": "Gameplay & VR Programmer",
    "timeline": "Graduation Project",
    "techStack": "Unity, C#, OpenXR, Quest 3S, AI Backend",
    "media": [
      {
        "type": "youtube",
        "label": "HIREQUEST",
        "sub": "VR walkthrough video",
        "featured": true,
        "label2": "Walkthrough",
        "id": "LKFkmpykXtw",
        "src": "https://youtu.be/LKFkmpykXtw"
      },
      {
        "type": "text",
        "label": "UI",
        "sub": "World-space UI on Quest 3S"
      },
      {
        "type": "text",
        "label": "SHOT",
        "sub": "In-headset capture"
      }
    ],
    "sections": [
      {
        "heading": "The Goal",
        "body": "HireQuest drops you into a realistic VR interview run by an AI backend that asks questions and reacts in real time. The idea was a low-stakes place to practice, so you can get the nerves out before you're sitting across from an actual person."
      },
      {
        "heading": "What I Built",
        "list": [
          "XR Origin setup with Near-Far and Poke interactors",
          "World-space UI conversion so text stays readable on Quest 3S",
          "VRFollowUI and a custom VRKeyboardManager",
          "Fixes for the OpenXR controller rotation bug and the OpenGLES3 build issue"
        ]
      }
    ],
    "gallery": [],
    "links": []
  },
  {
    "id": "new-project",
    "title": "New Project",
    "subtitle": "",
    "tagline": "",
    "tags": [],
    "featured": false,
    "cover": {
      "type": "text",
      "label": "NEW",
      "sub": ""
    },
    "role": "",
    "timeline": "",
    "techStack": "",
    "media": [],
    "sections": [],
    "gallery": [],
    "links": []
  },
  {
    "id": "new-project-2",
    "title": "New Project",
    "subtitle": "",
    "tagline": "",
    "tags": [],
    "featured": false,
    "cover": {
      "type": "text",
      "label": "NEW",
      "sub": ""
    },
    "role": "",
    "timeline": "",
    "techStack": "",
    "media": [],
    "sections": [],
    "gallery": []
  }
];
